## Proyecto 1

Importar librerias

In [ ]:
import pandas as pd
import numpy as nps
import numpy as np
import os
os.system('cls')

0

Definicion de funciones:

In [12]:
def MultiplicarFila(M, num_fila, num_fila_multiplo):
    M_nueva = M.copy()
    # Escriba su código aquí: multiplique cada elemento de una fila por un número
    M_nueva[num_fila] =M_nueva[num_fila]*num_fila_multiplo
    return M_nueva

def SumarFilas(M, num_fila_1, num_fila_2, num_fila_1_multiple):
    M_nueva = M.copy()
    # Escriba su código aquí: multiplique una fila por un número y sume la fila con otra
    M_nueva[num_fila_2] =  M_nueva[num_fila_2]+num_fila_1_multiple*M_nueva[num_fila_1]
    return M_nueva

def IntercambiarFilas(M, fila_num_1, fila_num_2):
    M_nueva =M.copy()
    # Escriba su código aquí: Intercambie fila_num_1 y fila_num_2 de la matriz M_nueva
    M_nueva[[fila_num_1, fila_num_2]] = M_nueva[[fila_num_2, fila_num_1]]
    return M_nueva

In [13]:
A_test = np.array([
        [1, -2, 3, -4],
        [-5, 6, -7, 8],
        [-4, 3, -2, 1],
        [8, -7, 6, -5]
    ], dtype=np.dtype(float))

print("Matriz original:")
print(A_test)

Matriz original:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [-4.  3. -2.  1.]
 [ 8. -7.  6. -5.]]


In [14]:
print("\nMatriz original después de multiplicar su tercera fila por -2:")
print(MultiplicarFila(A_test, 2, -2))

print("\nMatriz original después de intercambiar la tercera fila con la suma de sí misma y la primera fila multiplicada por 4:")
print(SumarFilas(A_test, 0, 2, 4))

print("\nMatriz original después de intercambiar su primera y tercera filas:")
print(IntercambiarFilas(A_test, 0, 2))
print('\n',A_test)


Matriz original después de multiplicar su tercera fila por -2:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [ 8. -6.  4. -2.]
 [ 8. -7.  6. -5.]]

Matriz original después de intercambiar la tercera fila con la suma de sí misma y la primera fila multiplicada por 4:
[[  1.  -2.   3.  -4.]
 [ -5.   6.  -7.   8.]
 [  0.  -5.  10. -15.]
 [  8.  -7.   6.  -5.]]

Matriz original después de intercambiar su primera y tercera filas:
[[-4.  3. -2.  1.]
 [-5.  6. -7.  8.]
 [ 1. -2.  3. -4.]
 [ 8. -7.  6. -5.]]

 [[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [-4.  3. -2.  1.]
 [ 8. -7.  6. -5.]]
